[package]
name = "protein-folding"
version = "0.1.0"
edition = "2024"

[dependencies]
engine = { git = "https://github.com/connorslade/beam-time" }
image = "=0.25.6"
rand = "0.9.2"
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
